version: '3.6'
services:
  mysql:
    platform: linux/x86_64
    image: mysql:5.6
    ports:
        - "3306:3306"
    volumes: 
        - ./docker/data/mysql:/var/lib/mysql
    command: --lower_case_table_names=1
    environment: 
        MYSQL_ROOT_PASSWORD: "nodemvc2323"
        MYSQL_DATABASE: "nodemvc"